Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fdfac10d8b0>
Traceback (most recent call last):
  File "/home/jumpserver/anaconda3/envs/open-clip/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1358, in __del__
    self._shutdown_workers()
  File "/home/jumpserver/anaconda3/envs/open-clip/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1322, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/home/jumpserver/anaconda3/envs/open-clip/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/jumpserver/anaconda3/envs/open-clip/lib/python3.8/multiprocessing/popen_fork.py", line 44, in wait
    if not wait([self.sentinel], timeout):
  File "/home/jumpserver/anaconda3/envs/open-clip/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/home/jumpserver/anaconda3/envs/open-clip/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt:
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/jumpserver/anaconda3/envs/open-clip/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/jumpserver/anaconda3/envs/open-clip/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jumpserver/anaconda3/envs/open-clip/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 71, in _wrap
    pass  # SIGINT; Killed by parent, do nothing
KeyboardInterrupt